services:
  bilibili-live-tools:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: bilibili-live-tools
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    user: "${UID:-1000}:${GID:-1000}"
