services:
  bilibili-live-tools:
    image: ghcr.io/akuma-real/bilibili-live-tools:latest
    container_name: bilibili-live-tools
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
