services:
  bilibili-live-tools:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: bilibili-live-tools
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
